name: Multi-Enviroment Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        type: text
        description: Name
        default: World

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:

      - name: Pretend to Deploy Dev
        run: echo I am deploying to DEV!!

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: PROD
    steps:

      - name: Pretend to Deploy Prod
        run: echo I am deploying to PROD!!
